### ISSUE TITLE
System.ObjectDisposedException: ThreadLocal object has been deleted.

### ISSUE THREAD

**Issue by yarecky1** [NimaAra/Easy.MessageHub#19]
Hi,

I'm maintaining legacy VB.NET project where I'm forced to close my application after some idle time when user is away from computer. In first form I initialize `AutoCloseController` which is
* responsible for filtering messages
* ticking every second to send progress information to main and all other forms. When idle time is too long, timer reaches maximum allowed time (let's say 120 seconds) and last message is sent with `CurrentTime = 0` that triggers `DisposeAllFormsExceptMe` method.

```
private void StartAutoCloseService()
{
    _autoCloseToken = MessageHub.Subscribe<AutoCloseTimeElapsed>(e =>
    {
        if (IsClosing)
            return;

        if (e.CurrentTime > 0)
        {
            PbProgress.Maximum = e.MaximumTime;
            PbProgress.Value = e.CurrentTime;
        }
        else
        {
            My.Application.DisposeAllFormsExceptMe(this);
            Close();
        }
    });
    _autoCloseController = new AutoCloseController(this);
}
```
`DisposeAllFormsExceptMe` method closes all open forms in reverse order they were created.
```
public void DisposeAllFormsExceptMe(Form myForm)
{
    {
        var forms = My.Application.OpenForms;
        for (var i = forms.Count - 1; i >= 0; i -= 1)
        {
            if (forms.Item(i) != myForm)
            {
                forms.Item(i).Visible = true;
                forms.Item(i).Close();
            }
        }
    }
}
```
Probably this is a root cause of `System.ObjectDisposedException: ThreadLocal object has been deleted.`.

In one of the grand, grand child form I subscribe to some another unrelated message type and some service publishes it. When service tries to send a message I receive `System.ObjectDisposedException: ThreadLocal object has been deleted.`. 

The stack trace:
```
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at System.Threading.ThreadLocal`1.get_Value()
   at Easy.MessageHub.Subscriptions.GetTheLatestSubscriptions()
   at Easy.MessageHub.MessageHub.Publish[T](T message)
```
Veryfing MessageHub object I see `AllSubscriptions` list is empty.

![MessageHub ObjectDisposedException](https://user-images.githubusercontent.com/28206604/84407316-335b0c00-abfa-11ea-83a4-90ac0fb01000.png)

How do you propose to bypass the problem?

**Comment by yarecky1** [comment]
Ok... Running `DisposeAllFormsExceptMe()` and then `Close()` I closed all the forms. In first form inside `MyBase.FormClosing` event I had a cleaning:
```
MessageHub.ClearSubscriptions()
MessageHub.Dispose()
```
When all forms have been closed (including the first one), some code in service class had to run to the end and the last line of the method was `MessageHub.Publish(...)` which obviously couldn't work properly. What a messy app.

Issue can be closed.
